"""Fuse the LoRA adapter into the base model and convert to GGUF for Ollama.

Two steps, both shell-outs (so this module has no torch/mlx import cost):

1. ``mlx_lm.fuse`` — merges the LoRA weights into the base, producing a
   plain HF-format directory (safetensors + tokenizer + config).
2. ``llama.cpp``'s ``convert_hf_to_gguf.py`` — converts that directory to a
   single ``model.gguf`` file Ollama can load via a Modelfile.

Output: ``bench/dpo/checkpoints/<version>/fused/`` (the fused HF dir) plus
``bench/dpo/checkpoints/<version>/model.gguf`` and a ``Modelfile`` ready for
``ollama create`` on the inference host.

``convert_hf_to_gguf.py`` lives in the llama.cpp repo. We don't bundle it —
the user clones llama.cpp once and points ``--llama-cpp-dir`` (or the
``LLAMA_CPP_DIR`` env var) at it. This keeps the wander repo small and lets
the user track llama.cpp on their own cadence.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_CHECKPOINT_ROOT = Path("bench/dpo/checkpoints")
DEFAULT_QUANT = "Q4_K_M"  # Ollama's default for 4B-class models; good size/quality.

MODELFILE_TEMPLATE = """# Generated by bench.dpo.fuse for wander DPO checkpoint {version}.
# Provenance: see bench/dpo/checkpoints/{version}/manifest.json
FROM ./model.gguf

# Gemma 3/4 chat template. Mirrors what mlx-lm and HF tokenizers apply.
TEMPLATE \"\"\"{{{{- if .System }}}}<start_of_turn>user
{{{{ .System }}}}

{{{{ .Prompt }}}}<end_of_turn>
{{{{- else }}}}<start_of_turn>user
{{{{ .Prompt }}}}<end_of_turn>
{{{{- end }}}}
<start_of_turn>model
{{{{ .Response }}}}<end_of_turn>
\"\"\"

PARAMETER stop "<end_of_turn>"
PARAMETER stop "<start_of_turn>"
"""


class FuseError(RuntimeError):
    pass


def _resolve_base_model(explicit: str | None, manifest: dict | None) -> str:
    """Use the same base the train run recorded, unless explicitly overridden."""
    if explicit:
        return explicit
    if manifest and (base := manifest.get("base_model")):
        return str(base)
    env = os.environ.get("WANDER_DPO_BASE_MODEL")
    if env:
        return env
    raise FuseError(
        "no base model specified — pass --base-model, run train.py first "
        "(its manifest records the base), or set WANDER_DPO_BASE_MODEL."
    )


def _resolve_llama_cpp_dir(explicit: Path | None) -> Path:
    if explicit:
        return explicit
    env = os.environ.get("LLAMA_CPP_DIR")
    if env:
        return Path(env)
    raise FuseError(
        "llama.cpp directory not found — pass --llama-cpp-dir or set LLAMA_CPP_DIR "
        "to a cloned llama.cpp tree (https://github.com/ggerganov/llama.cpp)."
    )


def _run(cmd: list[str], log_path: Path, label: str) -> None:
    with log_path.open("a", encoding="utf-8") as f:
        f.write(f"\n# === {label} ===\n# {' '.join(cmd)}\n")
        f.flush()
        rc = subprocess.call(cmd, stdout=f, stderr=subprocess.STDOUT)
    if rc != 0:
        raise FuseError(f"{label} failed (exit {rc}) — see {log_path}")


def fuse(
    *,
    version: str,
    checkpoint_root: Path = DEFAULT_CHECKPOINT_ROOT,
    base_model: str | None = None,
    llama_cpp_dir: Path | None = None,
    quant: str = DEFAULT_QUANT,
) -> Path:
    checkpoint_dir = checkpoint_root / version
    if not checkpoint_dir.is_dir():
        raise FuseError(f"{checkpoint_dir} not found — run `bench.dpo.train` first")

    manifest_path = checkpoint_dir / "manifest.json"
    manifest = None
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text())
        except (OSError, json.JSONDecodeError):
            manifest = None

    resolved_base = _resolve_base_model(base_model, manifest)
    llama_dir = _resolve_llama_cpp_dir(llama_cpp_dir)
    convert_script = llama_dir / "convert_hf_to_gguf.py"
    if not convert_script.is_file():
        raise FuseError(
            f"{convert_script} not found — llama.cpp layout may have changed; "
            "pin a known-good revision."
        )

    fused_dir = checkpoint_dir / "fused"
    gguf_path = checkpoint_dir / "model.gguf"
    modelfile_path = checkpoint_dir / "Modelfile"
    log_path = checkpoint_dir / "fuse.log"

    if shutil.which("python") is None and shutil.which(sys.executable) is None:
        raise FuseError("no Python interpreter available for subprocess")

    log_path.write_text(f"# fuse run for version {version}\n")

    _run(
        [
            sys.executable, "-m", "mlx_lm.fuse",
            "--model", resolved_base,
            "--adapter-path", str(checkpoint_dir),
            "--save-path", str(fused_dir),
        ],
        log_path, "mlx_lm.fuse",
    )

    _run(
        [
            sys.executable, str(convert_script),
            str(fused_dir),
            "--outfile", str(gguf_path),
            "--outtype", _outtype_for_quant(quant),
        ],
        log_path, "convert_hf_to_gguf",
    )

    modelfile_path.write_text(MODELFILE_TEMPLATE.format(version=version))
    return gguf_path


def _outtype_for_quant(quant: str) -> str:
    """Map an Ollama-style quant tag to convert_hf_to_gguf.py's --outtype.

    convert_hf_to_gguf produces an f16/bf16/q8_0 GGUF; further quantization
    (Q4_K_M etc.) typically happens with llama.cpp's `quantize` binary. For
    the scaffold we ship f16 by default — small enough for a 4B model, and
    the user can run `quantize` themselves if they want a smaller artifact.
    """
    if quant.upper() == "F16":
        return "f16"
    if quant.upper() == "BF16":
        return "bf16"
    # Anything else: emit f16 and let the user post-process with llama.cpp's
    # `quantize` binary. We don't shell out to it here to keep the dep
    # surface small.
    return "f16"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="bench.dpo.fuse")
    p.add_argument("--version", required=True)
    p.add_argument("--checkpoint-root", type=Path, default=DEFAULT_CHECKPOINT_ROOT)
    p.add_argument("--base-model", default=None,
                   help="HF/MLX base model id (defaults to the value recorded in train manifest).")
    p.add_argument("--llama-cpp-dir", type=Path, default=None,
                   help="Path to a cloned llama.cpp tree (defaults to $LLAMA_CPP_DIR).")
    p.add_argument("--quant", default=DEFAULT_QUANT,
                   help=f"Quant tag for the Modelfile name (default: {DEFAULT_QUANT}). "
                        "Note: scaffold emits f16 GGUF; use llama.cpp's `quantize` for smaller variants.")
    args = p.parse_args(argv)
    try:
        gguf = fuse(
            version=args.version,
            checkpoint_root=args.checkpoint_root,
            base_model=args.base_model,
            llama_cpp_dir=args.llama_cpp_dir,
            quant=args.quant,
        )
    except FuseError as e:
        print(f"fuse failed: {e}", file=sys.stderr)
        return 2
    print(f"gguf:      {gguf}")
    print(f"modelfile: {gguf.parent / 'Modelfile'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
